#!/usr/bin/env bash

sudo -v
cd ~

xcode-select -install

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

BREW=(
    cask
    git
    mas
    sass
    python
    ffmpeg
    youtube-dl
)

CASK=(
    visual-studio-code
    docker
    firefox
    mysqlworkbench
    discord
)

MAS=(
    497799835 # Xcode
    1278508951 # Trello
    409183694 # Keynote
    1091189122 # Bear
    409201541 # Pages
    409203825 # Numbers
)

brew update
brew upgrade

brew install ${BREW[@]}
brew cask install ${CASK[@]}
mas install ${MAS[@]}
